#!/usr/bin/env bash

# Set these variables to your own values
WALLET_PASSWORD="MsThXC7UM"

# Function to perform registration
perform_registration() {
    expect <<EOF
    set timeout -1
    spawn btcli s register --subtensor.network local --subtensor.chain_endpoint 45.131.139.137:9944 --netuid 27 --wallet.name coldkeyHK3 --wallet.hotkey hotkeyHK3
    expect {
        -re "Do you want to continue.*" {
            send -- "y\r"
            exp_continue
        }
        "Enter password to unlock key:" {
            send -- "$WALLET_PASSWORD\r"
            exp_continue
        }
        -re "Recycle.*" {
            send -- "y\r"
            exp_continue
        }
        -re "Balance:.*" {
            sleep 5;;
            exit 0
        }
        -re ".*Insufficient balance.*" {
            send_user "Insufficient balance detected\n"
            exit 2
        }
        eof {
            exit 1
        }
    }
EOF
    return $?
}

# Loop until the registration is successful
while true; do
    perform_registration
    result=$?

    case $result in
        0) echo "Registration Successful"
	   /bin/bash startme.sh
	   break ;;
        1) echo "EOF or unexpected error, retrying... in 5 seconds"
           sleep 5 ;;
        2) echo "Insufficient balance detected, retrying... in 5 seconds"
           sleep 5 ;;
        *) echo "Unknown error, retrying... in 5 seconds"
           sleep 5 ;;
    esac
done
